--------------------------------------------------------
--  Fichier créé - mercredi-juin-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECOLTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RECOLTE" 
   (	"ID_RECOLTE" NUMBER, 
	"CULTURE" VARCHAR2(20 BYTE), 
	"MASSE" FLOAT(126), 
	"PRIX" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.RECOLTE
SET DEFINE OFF;
Insert into SYSTEM.RECOLTE (ID_RECOLTE,CULTURE,MASSE,PRIX) values ('1','bananae','10','2,5');
Insert into SYSTEM.RECOLTE (ID_RECOLTE,CULTURE,MASSE,PRIX) values ('2','fraise','10','2,5');
Insert into SYSTEM.RECOLTE (ID_RECOLTE,CULTURE,MASSE,PRIX) values ('15','kiwi','10,5','2,5');
Insert into SYSTEM.RECOLTE (ID_RECOLTE,CULTURE,MASSE,PRIX) values ('5','manga','15','15');
Insert into SYSTEM.RECOLTE (ID_RECOLTE,CULTURE,MASSE,PRIX) values ('3','carotte','5','5');
Insert into SYSTEM.RECOLTE (ID_RECOLTE,CULTURE,MASSE,PRIX) values ('22','tomate','2,2','18,5');
Insert into SYSTEM.RECOLTE (ID_RECOLTE,CULTURE,MASSE,PRIX) values ('4','bles','6','7');
--------------------------------------------------------
--  DDL for Index RECOLTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RECOLTE_PK" ON "SYSTEM"."RECOLTE" ("ID_RECOLTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger RECOLTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."RECOLTE_TRG" 
BEFORE INSERT ON RECOLTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_RECOLTE IS NULL THEN
      SELECT RECOLTE_SEQ4.NEXTVAL INTO :NEW.ID_RECOLTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."RECOLTE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table RECOLTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RECOLTE" ADD CONSTRAINT "RECOLTE_PK" PRIMARY KEY ("ID_RECOLTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RECOLTE" MODIFY ("ID_RECOLTE" NOT NULL ENABLE);
